"""Generate ``docs/PARAMETERS.md`` from the three registries.

Usage (with the project venv active)::

    python -m pdsim.gendocs

``docs/PARAMETERS.md`` is a **committed** file, regenerated by this command
and guarded by a pytest drift test (DECISIONS #56): the test regenerates the
document in memory and compares it to the committed file, so a stale document
is a failing test — the same structural-impossibility pattern as the
Parameter Registry itself. When the drift test fails, run the command above
and stage the result.

Every word of parameter text below comes from the registries — the Parameter
Registry (``pdsim/config/registry.py``), the Strategy Registry
(``pdsim/core/strategies/registry.py``), and the Scenario Registry
(``pdsim/config/scenarios.py``); nothing is hand-written here. The output is
deterministic (registry/definition order only, no timestamps or environment
data), which is what makes an exact-comparison drift test possible.

This module lives at the package top level, beside ``run.py``, on purpose:
like the CLI it *orchestrates* the config and core registries (DECISIONS
#48) — and per hard rule 4 it imports no UI or plotting code.
"""

from __future__ import annotations

import sys
from pathlib import Path

from pdsim.config.registry import ParameterSpec, all_specs
from pdsim.config.scenarios import all_scenarios
from pdsim.core.strategies import all_strategies

DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "PARAMETERS.md"
"""Where the generated document lives: ``docs/PARAMETERS.md`` in the repo."""

_HEADER = """\
# Parameter Reference

> **GENERATED FILE — do not hand-edit.** Regenerate with
> `python -m pdsim.gendocs`. A pytest drift test compares this file to a
> fresh regeneration, so hand edits (or a stale copy) fail the suite.

Everything below is generated from the platform's registries — the Parameter
Registry (`pdsim/config/registry.py`), the Strategy Registry
(`pdsim/core/strategies/registry.py`), and the Scenario Registry
(`pdsim/config/scenarios.py`). Those registries are the single source of
truth: the same text appears as tooltips in the app, and a parameter cannot
exist without an entry here.
"""

_KIND_LABELS = {
    "int": "whole number",
    "float": "number",
    "bool": "true/false",
    "choice": "choice",
}
"""Novice-facing names for the registry's parameter kinds."""


def _format_number(value: float) -> str:
    """Format a numeric bound compactly (no trailing ``.0`` on integers).

    Args:
        value: The bound to format.

    Returns:
        E.g. ``"100"`` for 100.0 and ``"0.98"`` for 0.98.
    """
    return f"{value:g}"


def _format_range(spec: ParameterSpec) -> str:
    """Describe a spec's allowed values in one plain-language phrase.

    Args:
        spec: The parameter whose range/choices to describe.

    Returns:
        E.g. ``"0 to 1"``, ``"0 to below 1"``, ``"at least 1"``,
        ``"one of: `round_robin`, `random_k`"``, or ``"true or false"``.
    """
    if spec.kind == "bool":
        return "true or false"
    if spec.kind == "choice":
        options = ", ".join(f"`{choice}`" for choice in spec.choices or ())
        return f"one of: {options}"
    parts: list[str] = []
    if spec.minimum is not None and spec.maximum is not None:
        upper = _format_number(spec.maximum)
        if spec.maximum_exclusive:
            upper = f"below {upper}"
        parts.append(f"{_format_number(spec.minimum)} to {upper}")
    elif spec.minimum is not None:
        parts.append(f"at least {_format_number(spec.minimum)}")
    elif spec.maximum is not None:
        bound = _format_number(spec.maximum)
        parts.append(f"below {bound}" if spec.maximum_exclusive else f"at most {bound}")
    else:
        parts.append("unbounded")
    if spec.nullable:
        parts.append("may be empty (= off/unlimited)")
    return "; ".join(parts)


def _format_default(spec: ParameterSpec) -> str:
    """Render a spec's default value as inline markdown.

    Args:
        spec: The parameter whose default to render.

    Returns:
        A backticked literal, or ``"empty (no limit)"`` for None defaults.
    """
    default = spec.default
    if default is None:
        return "empty (no limit)"
    if isinstance(default, bool):
        return "`true`" if default else "`false`"
    if isinstance(default, str):
        return f"`{default}`"
    return f"`{default!r}`"


def _parameter_block(spec: ParameterSpec, heading: str) -> list[str]:
    """Render one parameter as a markdown block.

    Used for both simulation parameters and strategy parameters, so every
    parameter in the document reads the same way.

    Args:
        spec: The parameter to render.
        heading: The markdown heading prefix, e.g. ``"###"``.

    Returns:
        The block's lines (heading, facts, description, learn-more note).
    """
    lines = [
        f"{heading} `{spec.key}` — {spec.label}",
        "",
        f"- **Type:** {_KIND_LABELS[spec.kind]}",
        f"- **Allowed values:** {_format_range(spec)}",
        f"- **Default:** {_format_default(spec)}",
        "",
        spec.description,
    ]
    if spec.learn_more:
        lines += ["", f"*Learn more:* {spec.learn_more}"]
    lines.append("")
    return lines


def generate_parameters_markdown() -> str:
    """Build the complete ``docs/PARAMETERS.md`` content.

    Deterministic by construction: sections appear in registry registration
    order, strategies and scenarios in their registries' display order, and
    nothing environment-dependent (timestamps, versions, paths) is included.

    Returns:
        The full markdown document, ending in a single newline.
    """
    lines: list[str] = [_HEADER]

    # --- Simulation parameters, grouped by registry section --------------
    # Strategy parameters (keys under "strategy.") are excluded here; they
    # appear with their strategies in the roster section below, exactly as
    # the UI shows them in the per-strategy expander.
    lines += [
        "## Simulation parameters",
        "",
        "Grouped by section, in the order the app's parameter panel shows them.",
        "Strategy-specific parameters appear with their strategies further down.",
        "",
    ]
    sections: dict[str, list[ParameterSpec]] = {}
    for spec in all_specs():
        if not spec.key.startswith("strategy."):
            # dict preserves insertion order, so sections keep first-appearance
            # (= registry) order.
            sections.setdefault(spec.section, []).append(spec)
    for section, specs in sections.items():
        lines += [f"### {section}", ""]
        for spec in specs:
            lines += _parameter_block(spec, "####")

    # --- Strategy roster ---------------------------------------------------
    lines += [
        "## Strategy roster",
        "",
        "Every playable strategy, in display order. The machine name in",
        "parentheses is the identifier configs use (e.g. in",
        "`population.composition`).",
        "",
    ]
    for info in all_strategies():
        lines += [f"### {info.display_name} (`{info.name}`)", "", info.description]
        if info.learn_more:
            lines += ["", f"*Literature note:* {info.learn_more}"]
        lines.append("")
        if info.params:
            for spec in info.params:
                lines += _parameter_block(spec, "####")
        else:
            lines += ["This strategy has no tunable parameters.", ""]

    # --- Scenarios -----------------------------------------------------------
    lines += [
        "## Scenarios",
        "",
        "Curated, ready-to-run presets from the Scenario Registry. Each is a",
        "complete experiment configuration; in the app, pick one from the",
        "scenario dropdown and every parameter stays editable.",
        "",
    ]
    for scenario in all_scenarios():
        lines += [
            f"### {scenario.display_name} (`{scenario.name}`)",
            "",
            scenario.description,
            "",
            f"**Things to try:** {scenario.things_to_try}",
            "",
        ]

    # Join with single newlines; blocks already end in "" so blank lines
    # separate them. Strip any run of trailing blanks down to one newline.
    return "\n".join(lines).rstrip("\n") + "\n"


def write_parameters_doc(path: Path | None = None) -> Path:
    """Generate the document and write it to disk (LF line endings).

    Args:
        path: Destination file; defaults to :data:`DEFAULT_OUTPUT`
            (``docs/PARAMETERS.md`` in the repository).

    Returns:
        The path written to.
    """
    target = DEFAULT_OUTPUT if path is None else Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" keeps the committed file byte-stable across platforms
    # (Windows would otherwise write CRLF and churn the diff/drift test).
    target.write_text(generate_parameters_markdown(), encoding="utf-8", newline="\n")
    return target


def main() -> int:
    """Run the generator as a command.

    Returns:
        Process exit code (always 0; registry errors would raise at import).
    """
    target = write_parameters_doc()
    print(f"Wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
